Repository surfstudio/flutter-surf-lint-rules, pull requests merged in 2023-07, with the labels that each got.

#29 feat: Dart 3 ready update
  example/lib/main.dart
  lib/analysis_options.3.0.0.yaml
  lib/analysis_options.yaml
  lib/surf_lint_rules.dart
  pubspec.yaml
Labels: enhancement, dependencies, new pull request

#31 chore: Update changelog file
  CHANGELOG.md
Labels: documentation, new pull request

#34 fix: Fix dependencies versions
  pubspec.yaml
Labels: bug, new pull request
