Repository surfstudio/flutter-surf-lint-rules, pull requests merged in 2023-02, with the labels that each got.

#16 feat: upgrade flutter_lints and dart_code_metrics
  CHANGELOG.md
  example/pubspec.yaml
  lib/analysis_options.2.0.0.yaml
  lib/analysis_options.yaml
  pubspec.yaml
Labels: enhancement, dependencies, new pull request

#21 feat: update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement, new pull request

#20 deyew: added pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new pull request
