Repository surfstudio/flutter-surf-lint-rules, pull requests merged in 2023-03, with the labels that each got.

#22 SNP-320 chore: added linter info to readme
  README.md
Labels: documentation, new pull request

#19 feat: Add new DCM rules
  lib/analysis_options.2.0.0.yaml
Labels: enhancement, new pull request

#23 no-task lint rules description links added
  README.md
Labels: documentation, new pull request

#24 SNP-320 chore: added dcm rules to readme.md
  README.md
  pubspec.yaml
Labels: documentation, new pull request

#27 SNP-320 chore: updated changelog
  CHANGELOG.md
Labels: documentation
